var rls="Remember Last Summer";
var artist="Nxxxxxs";
var copr="© 2017 Headcount Records";
var reldat="26.05.17";
var one="Remember Last Summer (title track)";
var two="1000 Ways To Get Paid";
var three="Come Home 2nite";
var four="Evil Thoughts Be On My Mind (feat. Souidere)";
var five="Shoot It In The Heart";
var six="Everybody Is A Suspect";
var seven="If It Was A Deer Then Where Is It (feat. Senpu)";
var eight="Diamonds Part. 3 (feat. Senpu)";
var nine="Death Has Come To Your Little Town";
var ten="Now The Time Has Come To Wake Up";
var eleven="Happy Fourth Of July Julie";
var twelve="1000 Blunts";

document.write(rls,"by",artist,"\n");
document.write("01.",one);
document.write("02.",two);
document.write("03.",three);
document.write("04.",four);
document.write("05.",five);
document.write("06.",six);
document.write("07.",seven);
document.write("08.",eight);
document.write("09.",nine);
document.write("10.",ten);
document.write("11.",eleven);
document.write("12.",twelve);
document.write("Release Date:",reldat);
document.write(copr);
